# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa699c31b8f850d937733b649e13e529d75607beb1b56f6e7e57e27cf072ad352f1f22c81058f286a3e3feb6b7d1304e6256aa9a2cbe5d91afa9e2af2ecf86a2

test:
  secret_key_base: c315cc1f85be4185d7c7d519ee0ee499e33bb9eff2fdf6d0dddc9f31754a5d7e464daed6433e09548960ebd244d850cb13d6c1b23a093216b3703b979f4c0016

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
